### ISSUE TITLE
Group operation and their options better 

### ISSUE THREAD

**Issue by peteruithoven** [tbfleming/jscut#12]
So currently users create and select the current operation in the top left. The options for the selected operation then appear bottom left. Understanding this connection can difficult at first. 

My suggestion would be to group this better, maybe have a kind of fold-in, fold-out system. Like a accordion menu, but without the forged limit that only one item can be open. 
![operations](https://cloud.githubusercontent.com/assets/523210/3870780/86857f94-20de-11e4-8fd6-1939f6dbb022.png)

So users always see the basic options per operation, like it currently shows the _Visible_, _Combine_ and _Operation_ options. (I would personally skip _Combine_ here.)
Then when the users folds out the operation he sees options like _Ramp Plunge_, _Direction_, _Cut depth_, _Margin_ etc. 
A extra feature would be that users could use the scrubbers to drag the operations and change the order. 

What do you guys think?

**Comment by tbfleming** [comment]
I like this

**Comment by peteruithoven** [comment]
Let me know if I can do anything, being more specific in certain aspects for example.

**Comment by peteruithoven** [comment]
Nice! 
Good detail that u used text for the arrow, that keeps it sharp on screens with a higher dpi.
