### ISSUE TITLE
Changing html broke databinding? 

### ISSUE THREAD

**Issue by peteruithoven** [tbfleming/jscut#16]
I wanted to improve the style of the operations, but changing the html somehow broke the databinding. 
My changes: 
https://github.com/peteruithoven/jscut/commit/f78ad00ad1b414e986942028db478139af7c32d1

What could be wrong?

**Comment by tbfleming** [comment]
You can't place a div directly in a table.

**Comment by tbfleming** [comment]
See Note 4 for a workaround at http://knockoutjs.com/documentation/foreach-binding.html

**Comment by tbfleming** [comment]
Further down the rabbit hole: http://stackoverflow.com/questions/8115896/knockout-js-containerless-foreach-not-working-with-table

**Comment by peteruithoven** [comment]
Thanks for the tips!
