### ISSUE TITLE
Replace Get button with FileSaver or similar

### ISSUE THREAD

**Issue by tytouf** [tbfleming/jscut#18]
Instead of displaying the file (settings or gcode) by clicking the button Get and then require the user to save the page as a file, it is possible to more directly save files as described here http://updates.html5rocks.com/2011/08/Saving-generated-files-on-the-client-side.

**Comment by tbfleming** [comment]
Any chance you'd be willing to do it and send me a pull request?

**Comment by tytouf** [comment]
Yes I was planning to work on that after the local storage.
