### ISSUE TITLE
'GET' settings files localling instead of just on google drive

### ISSUE THREAD

**Issue by g19fanatic** [tbfleming/jscut#2]
It would be useful to be able to be able to reach these files locally as well as on Google Drive (as we can run jscut locally and not just on the web).

**Comment by g19fanatic** [comment]
I did just see the todo list and this is one of the items in that list. Didn't see that before. I apologize if you feel this is superfluous in nature to have it in two places.

**Comment by tbfleming** [comment]
I'm OK with duplicates. Issues let me know what users actually want; the todo list doesn't do that.

**Comment by tbfleming** [comment]
Done
