### ISSUE TITLE
makeAllSameUnit() makes objects impossible to select which have had an operation created and deleted

### ISSUE THREAD

**Issue by andrewhodel** [tbfleming/jscut#27]
1. load svg
2. select object or multiple objects
3. create operation with default settings
4. delete that operation
5. click Make all mm

At this point the object you previously selected and created/deleted an operation for becomes un-selectable.  It does the same thing if you do it in reverse by using MM prior to creating/deleting the operation then using Make all inch.

**Comment by tbfleming** [comment]
Yikes! Good catch, easy to reproduce.

**Comment by tbfleming** [comment]
Fixed for above case. Problem still exists in tabs because of UnitConverter.
