### ISSUE TITLE
Material thickness ignored (makes a single pass)

### ISSUE THREAD

**Issue by CarlosGS** [tbfleming/jscut#28]
First of all, thanks for this software as it is very useful and user-friendly :)

It has been a bunch of times I have got the following error: The amount of passes when creating a cut operation isn't calculated properly.
http://jscut.org/jscut.html?gist=e1f42b8e339a2db06ec8
![screenshot from 2014-10-21 12 27 17](https://cloud.githubusercontent.com/assets/1636266/4717462/3be9a5ea-5915-11e4-9191-597b800acd2f.png)
As you can see (after pressing Generate) the result contains only a single pass.

The problem has appeared with various configurations: Linux & Chrome, Linux & Firefox, Windows & Chrome, etc. I'm sorry as I don't know how to debug the issue. Maybe I am doing something wrong?

Thanks again!!

**Comment by peteruithoven** [comment]
The cutting depth is a setting you can find by "folding open" the operation settings, by pressing the arrow next to generate. 
I hope to make this button more notable in the future, putting it at the beginning of the line for example. I would also like to give the operations a more bar look, so it makes more sense that they can be folded open. 
I'm actually not sure what the material depth is used for when the Z origin is Top.

**Comment by tbfleming** [comment]
Thickness does nothing when the Z origin is Top.

Peter: thanks for answering this! I suspect that moving it to the left will make it less visible. What if we make the "show additional detail" popup appear as soon as the user clicks "create operation"?

**Comment by peteruithoven** [comment]
That could work, but feels a bit like a hack. 
I'll think about this, this evening. Maybe we should also show Cut depth in the closed mode, but then it probably requires some extra styling for grouping or a different kind of input fields. 

Maybe we could help people learn the arrow by using it in the other panels and having panels like _Tabs_, _Curve to Line conversion_ and _Gcode Conversion_ closed by default, but I remember that you didn't like that idea.

**Comment by CarlosGS** [comment]
Oh I see! Thanks for pointing that out. I simply interpreted the arrow as "play" or "go".
Had never seen those options, they are very useful indeed. Jscut gets even more awesome :P

I'd go for something more clear, definitely giving more importance to the hidden parameters. For instance a "More options" link next to the operation type. The arrow could be kept in place as well :)

Thanks again!!!
