### ISSUE TITLE
Operation fold-out, fold-in improvements

### ISSUE THREAD

**Issue by peteruithoven** [tbfleming/jscut#29]
I'm seeing a lot of people looking over the operation fold-out button. One comment was that next to the generate button it might be confused with a go / play button. 

I think there are a few things we can do: 
- Create a bit more space between the generate and the fold-out arrow
- Place the arrow somewhere else. (see B)
- Choose a slightly different style arrow
- Give the operations a more accordion look. Giving them a background color for example.  
- Add the cutting depth (one of the most important settings per operation) to the bar. 

![operations2](https://cloud.githubusercontent.com/assets/523210/4725697/c41f8b46-595b-11e4-92e9-97e9ca31d1ec.png)

I think option B is better, because the fold button is less grouped with the generate link. 
Feedback is welcome. 
I'd like to help out with the css / html where needed.

**Comment by DavidMenting** [comment]
Option B seems like the best way to tackle this problem, as option A is not really a solution to the confusion. Should be easy to implement in a few minutes.

Adding the cutting depth to the overview would be a big usability improvement, as it allows you to catch errors more easily when setting up a cutting job. In a future revision, more settings could be added to the overview responsively, based on the browser-width like so:

> Pocket  generate
> Pocket 3 deep generate
> Pocket 3 mm deep with 0.2 mm margin generate

**Comment by peteruithoven** [comment]
I like the responsive idea, but I really hope there is a way to do this without lot's of media query's. 

I think I'll try to use the panel classes from Bootstrap to get the accordion look
http://getbootstrap.com/javascript/#collapse

**Comment by tbfleming** [comment]
Peter, go ahead and try the panel idea to see how it looks. "Operations" is already a panel; it will be interesting to see if nested panels look well and if they combine well with the table format.

**Comment by peteruithoven** [comment]
Very nice, you already implemented the idea! I really hope this will help people find these settings. 
![screen shot 2014-10-28 at 22 04 49](https://cloud.githubusercontent.com/assets/523210/4817198/8069b26a-5ee6-11e4-8ac5-a411d4011b6b.png)

I find I can hardly make the time. When I find the time I notice that I'm mostly trying to move inline styles into the css file. So maybe my next pull request will mostly be style moves. 
I'm also struggling with the table system, because it's not very flexible. It for example doesn't allow me to change to two lines when it doesn't fit anymore. But then again working with float has quite some issues too.
