### ISSUE TITLE
Inch/MM for Depth and Margin

### ISSUE THREAD

**Issue by ghost** [tbfleming/jscut#3]
Cut Depth still only inch  
Margin still only inch

**Comment by tbfleming** [comment]
The Units setting in the Material panel controls Cut Depth and Margin. I'm marking this as a bug since it causes confusion. I'll probably place a new Units setting in Selected Operation.

**Comment by tbfleming** [comment]
Selected Operation now has separate units

**Comment by ghost** [comment]
Fantastic thanks.

Do you accept gifts by any chance?  

peter@openhardware.co.za (can't find you on G+?)

Want to send you a set of https://www.facebook.com/photo.php?fbid=731441166915677&l=15fa73e686 GrblPi+Stepper drivers assembled and tested.

The one thing DIY CNC has needed for years is a good CAM and yours so far impressed me most... Especially at what is in essence a new project!

Working with Andrew Hodel as well with GrblWeb (Sending him a set as well)

Also happy to discuss licencing option (or just forced donation per sale) with out CNC kit... if you are interested.  I know open source development can sometimes feel like a dead end due to the little thanks and even less income from it.  I started OpenHardware.co.za in 2011 with the idea to help fund and develop good opensource ideas and help them get sold.  Just trying to make a difference.

Sorry about the Git message - contact me so I can get your off thread contact details and shipping address please

Peter
