### ISSUE TITLE
Make all inches/mm

### ISSUE THREAD

**Issue by tiger12506** [tbfleming/jscut#38]
![jscut-1](https://cloud.githubusercontent.com/assets/1036922/7876049/6769fe4c-0593-11e5-8081-52e06323b3b6.JPG)

From my perspective, it looks like the "Make all mm" and "Make all inch" links should convert, but the drop-down should not convert, just read the current values as the specified units.

This is currently not the case, as both the drop-down and the link convert the values in the fields.

**Comment by g19fanatic** [comment]
I believe having two ways of changing is unnecessarily redundant. I would opt for changing the drop-down to a label to declare what unit is being used and just keep the "Make all" actions.

**Comment by tbfleming** [comment]
There are multiple independent units fields. The "Make all" links set all of them at once.

**Comment by tiger12506** [comment]
Ok, so this doesn't actually duplicate functionality then, because the Make all links affect more than just the Material grouping. Got it. I'd still be interested in a "change how we interpret the numbers without converting the numbers" feature, but certainly not a deal-breaker in any way, of course.

I greatly appreciate the work you are doing here.
