### ISSUE TITLE
V Bits

### ISSUE THREAD

**Issue by g19fanatic** [tbfleming/jscut#4]
Would it be possible to add V bits? 

In the current version, it is not easy to do variable depth cuts using V bits since we're unable to change the tool for the operations.

**Comment by tbfleming** [comment]
I need help with this one finding an appropriate algorithm. This ticket is a good spot to collect links to published code, research papers, etc.

**Comment by g19fanatic** [comment]
Here are a few links that might help out some. I'll be looking into this myself as well.

http://www.scorchworks.com/Fengrave/fengrave.html
http://www.scorchworks.com/Fengrave/f-engrave_calculations.htm

http://www.anderswallin.net/cam/
https://github.com/aewallin/openvoronoi

http://www.payne.org/index.php/CNC_Projects#V-Carving
http://www.payne.org/index.php/Calculating_Voronoi_Nodes

**Comment by g19fanatic** [comment]
The Scorchworks f-engrave calculations page seems to be a great way to do this. At that page, he goes over all of the algebraic logic as well as steps through reducing the equations to the usable state.

Specific VCarve code starts at line 5686 of f-engrave-139.py which can be located at http://www.scorchworks.com/Fengrave/fengrave.html  and more specifically at http://www.scorchworks.com/Fengrave/F-Engrave-1.39_src.zip.

At the first link, it looks like the code is released with GPLv3. Besides this download section, I am unable to find an online source repository which leads me to believe he's not using a public one like github/bitbucket.

**Comment by tbfleming** [comment]
I'm using Boost.Polygon's Voronoi operations. Screen shots of what I have so far are at https://groups.google.com/forum/#!topic/jscut/VqTTq5AgmuA

**Comment by tbfleming** [comment]
New operation: V Pocket

I released what I have so far. Current limitations:
- It assumes an infinitely tall cutter. I plan to make it automatically pocket areas which are too wide in the future.
- It sometimes exceeds the video card memory limit. I have an approach in mind to fix that also.
