### ISSUE TITLE
Show me dimensions of everything

### ISSUE THREAD

**Issue by Harvie** [tbfleming/jscut#56]
I have imported SVG and then i set px per inch. That should be enough to show me how big will the picture be in real life... Maybe have some tool to check distance between two points in SVG... And after generating G-code we should also be able to compute total dimensions of it.

Something like ugs-platform does. It's super useful to check if dimensions are about sane in code:

![image](https://cloud.githubusercontent.com/assets/276504/25300131/b6dc94d8-2708-11e7-93a8-56ee8132ca55.png)

Right now i have to export g-code, check dimensions in ugs and then do another export if i need to fix something... I also think it should separately count negative and positive Z dimensions. Because stuff under Z0 is usualy what is actually being cut, while stuff over Z0 is just safety margin and moving over the stock. BTW this should also work when WebGL support is not available...

**Comment by tbfleming** [comment]
LaserWeb4 is jscut's successor. It supports this, but requires WebGL to function.

http://cncpro.co/

**Comment by Harvie** [comment]
LaserWeb4 is for laser cutters. Doesn't seem to be suitable for my milling machine...

**Comment by tbfleming** [comment]
LW4 is for a variety of machines; its name is historical from when it used to only support lasers. Look through the postings at https://plus.google.com/communities/115879488566665599508 ; you'll see examples where people used it for lasers, CNC routers, and some esoteric things like a motorized etch-a-sketch.

To enable milling machine support, turn on Settings -> Application -> Enable CNC Mode.

**Comment by Harvie** [comment]
So should i take jscut as officialy dead project? I am not really happy with LW4, and i prefer jscut. But i don't see the point why you're still accepting new issues, if you are not willing to continue with development...

**Comment by nsiatras** [comment]
I have to agree. I also prefer JSCut to LW. It is a better software for easy CNC operations.

**Comment by Harvie** [comment]
@nsiatras hey baby! wanna fork? :)

**Comment by nsiatras** [comment]
Wish I could. I am running a few heavy weight projects at the moment so no time for the community.
