### ISSUE TITLE
Rubber-banding to select multiple objects

### ISSUE THREAD

**Issue by leonerd** [tbfleming/jscut#59]
I have an 8x8 grid of 64 holes to drill. It would be convenient for me to drag a rubber-band box and select all 64 at once, instead of clicking each one individually.

**Comment by tbfleming** [comment]
I no longer add new features to jscut. LaserWeb got a whole new UI that uses jscut's engine: http://laserweb.github.io/LaserWeb4

**Comment by g19fanatic** [comment]
@leonerd you could just group/combine them in the svg to select them all at once
